export * from './tenants'
export * from './users'
export * from './academic'
export * from './enrollment'
export * from './student-enrollment'
export * from './scheduling'
export * from './syllabus'
export * from './obe'
export * from './assessment'
export * from './timetable'
export * from './class-schedule'
// export * from './assignments'
// export * from './quizzes'
// export * from './results'
